### ISSUE TITLE
macOS support (bwrap)

### ISSUE THREAD

**Issue by anton-trunov** [coq-tactician/coq-tactician#2]
First of all, let me thank you for this great tool! I'm really excited to try it.

As far as I understand, `bwrap` is Linux-specific. I can install Tactician on my machine and it works, but I cannot install any new Coq library after `tactician inject`. I get `bwrap: command not found`.

Is there a workaround for this?

Just in case, here is a typical output:
```shell
$ opam install coq-mathcomp-ssreflect
The following actions will be performed:
  ∗ install coq-mathcomp-ssreflect 1.12.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[coq-mathcomp-ssreflect.1.12.0] downloaded from https://github.com/math-comp/math-comp/archive/mathcomp-1.12.0.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of coq-mathcomp-ssreflect failed at "/Users/anton/.opam/opam-init/hooks/sandbox.sh build with-tactician make -C mathcomp/ssreflect -j 3".

#=== ERROR while compiling coq-mathcomp-ssreflect.1.12.0 ======================#
# context     2.0.7 | macos/x86_64 | ocaml-base-compiler.4.11.0 | https://coq.inria.fr/opam/released#2020-12-03 12:40
# path        ~/.opam/coq8.12-tactician/.opam-switch/build/coq-mathcomp-ssreflect.1.12.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build with-tactician make -C mathcomp/ssreflect -j 3
# exit-code   127
# env-file    ~/.opam/log/coq-mathcomp-ssreflect-19181-2dea01.env
# output-file ~/.opam/log/coq-mathcomp-ssreflect-19181-2dea01.out
### output ###
# /Users/anton/.opam/coq8.12-tactician/bin/with-tactician: line 18: bwrap: command not found



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build coq-mathcomp-ssreflect 1.12.0
└─
╶─ No changes have been performed
```

**Comment by LasseBlaauwbroek** [comment]
Thanks for the issue. This is indeed an unexpected problem (I tested on macOS but did not install packages). I'm using `bwrap` to inject Tactician into the build by mounting a different file on top of `coqc`. I do not immediately see a straightforward alternative to `bwrap` for macOS (maybe `sandbox-exec`, but I doubt it). I'll take another look next week, but this will be tricky because I have no apple hardware lying around.

I also cannot immediately think of an easy workaround (a workaround is possible, but you would have to be willing to manually rearrange some binaries in your opam installation; let me know if that is something you want to do).

Finally, I see that you are trying Tactician on mathcomp. In principle, this should work, but there is no special support for ssreflect yet. So you should not expect great results here.

**Comment by anton-trunov** [comment]
> but this will be tricky because I have no apple hardware lying around.

I can certainly help with that. Feel free to ping me anytime. Also, GitHub Actions provide support for macOS.

> manually rearrange some binaries in your opam installation; let me know if that is something you want to do

Sure, that would work for me. Thanks a lot.

> there is no special support for ssreflect yet. So you should not expect great results here.

Ah, I see. I think it's fine :) I understand the project is in beta. Thanks for the heads up.

**Comment by LasseBlaauwbroek** [comment]
> Sure, that would work for me. Thanks a lot.

Let `<prefix>` be your opam directory. Move `<prefix>/bin/coqc` to `<prefix>/bin/coqc.real`. Then create the following bash file in the place of `coqc` (with executable permissions):

```bash
#!/bin/bash
<prefix>/bin/coqc.real -q -I <prefix>/lib/coq/user-contrib/Tactician -R <prefix>/lib/coq/user-contrib/Tactician Tactician -rifrom Tactician Ltac1.Record  "$@"
```
(I'm writing this by hand, so you might need to correct some of my directory mistakes).

**Comment by LasseBlaauwbroek** [comment]
Oh, and with those instructions I should also say that you should run `tactician eject`, since you are now doing the injection manually. Then you should be able to install packages as normal.

**Comment by anton-trunov** [comment]
Works like a charm, thanks again!

FWIW, I see some warnings as follows but that expected as you pointed out above:
```
Warning:
Tactician is having problems with the following tactic. Please report. ssrrwarg
Warning:
Tactician is having problems with the following tactic. Please report. ssrhint3arg
```

And the tool suggests some nice proofs already.

**Comment by LasseBlaauwbroek** [comment]
Great! If you have any other feedback, let me know.

Regarding the warnings: Many of them have been resolved in Coq master. So switching to master may help a bit. But indeed, ssreflect is not very well tested yet so some of these warnings will remain.

**Comment by anton-trunov** [comment]
I'll switch to the dev version then, thank you.

**Comment by LasseBlaauwbroek** [comment]
Okay, I think that one possible replacement for `bwrap` could be [bindfs](https://bindfs.org/), based on FUSE. This would be a little heavy-handed though. I don't know how easy it is to install this on macOS. There seems to be a package available on [homebrew](https://formulae.brew.sh/formula/bindfs). Can you tell me if that would be a reasonable solution?

**Comment by LasseBlaauwbroek** [comment]
Ah, it seems that there is also a package for [macports](https://ports.macports.org/port/bindfs/summary), and both macports and homebrew are [supported](https://opam.ocaml.org/doc/Manual.html#opamvar-os-distribution) by the depext functionality of opam. So this may actually work.

**Comment by anton-trunov** [comment]
I installed `bindfs` using Homebrew to check if it is installable at all and I got the following warning:
```
Warning: bindfs has been deprecated because it requires FUSE!
```
I guess it's fine as a short-term solution but we might need something else in the future.

**Comment by LasseBlaauwbroek** [comment]
I did a bit more investigation:

- macOS does not have a notion of user namespaces like Linux does, which is why no alternative to `bwrap` exists (and cannot exist).
- I tried `bindfs`, but that can only mount directories and not single files, which complicates matters quite a bit. In addition, it cannot mount directories on top of read-only directories. This is a problem because Opam runs in a sandbox, created by `sandbox-exec` on macOS. So to use a `bindfs` solution you'd have to disable Opam's sandbox.
- The only other solution I can think of is to use `mount --bind`, but for that you need superuser rights (at least in Linux, and presumably also macOS). So that's also a far-from-perfect solution.

**Comment by LasseBlaauwbroek** [comment]
Before I used the `bwrap` solution I modified the `PATH` environment variable (and many related variables like `COQBIN` and `COQCEXTRAFLAGS`). This is not super reliable, but it may be the only reasonable solution here.

**Comment by anton-trunov** [comment]
> This is not super reliable, but it may be the only reasonable solution here.

I agree but I must admit I'm really out of my depth with this issue :)

**Comment by LasseBlaauwbroek** [comment]
I've now made a fallback to `PATH`-manipulations when `bwrap` is not available. I'm still not entirely happy about this, because at least the HoTT library does not work with that. But I don't see any other solution. Can you test this on your mac? There are branches for:
- 8.11 https://github.com/coq-tactician/coq-tactician/tree/macos-fix
- 8.12 https://github.com/coq-tactician/coq-tactician/tree/macos-fix8.12
- 8.13 https://github.com/coq-tactician/coq-tactician/tree/macos-fix8.13
- dev https://github.com/coq-tactician/coq-tactician/tree/macos-fixdev

(You can install one of these branches by cloning and then running `opam install . -w` inside their directory. Don't forget to undo the binary shuffling you did.)

**Comment by anton-trunov** [comment]
Worked like a charm! I moved the `coq.real` binary back in place and tried the branch for Coq 8.12 (https://github.com/coq-tactician/coq-tactician/tree/macos-fix8.12). The `coq-mathcomp-ssreflect` package compiled just fine. Thank you!

**Comment by LasseBlaauwbroek** [comment]
Thanks for trying it out. Just to confirm, did you run `tactician inject` again, and verify that the system has actually learned?

**Comment by anton-trunov** [comment]
Yes, I did run `tactician inject` (at that point I was offered to reinstall the previously installed `coq-mathcomp-ssreflect` package) and checked that `Suggest` suggests reasonable options.

**Comment by LasseBlaauwbroek** [comment]
Thanks. I've merged the branches. I also fixed some of the warnings you mentioned. But you will probably still get "printing/parsing" warnings because those need to be fixed upstream.

I'm closing this for now. If ever a better solution for macOS presents itself we can revisit.

**Comment by anton-trunov** [comment]
Great, thank you for the fixes!
