### ISSUE TITLE
Error installing coq-tactician-stdlib

### ISSUE THREAD

**Issue by sgodwincs** [coq-tactician/coq-tactician#45]
Following the installation directions on the homepage, I encounter the following error when running `opam install coq-tactician-stdlib` (also when running `tactician inject`):

```
The following actions will be performed:
  * install coq-tactician-stdlib 8.13.dev  *** WARNING ***
                                                              This package will overwrite Coq's standard library files.
                                                              A backup of the original files will be placed under Coq's
                                                              library directory at user-contrib/tactician-stdlib-backup/
                                                              and they will be restored when you remove this package

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
retrieved coq-tactician-stdlib.8.13.dev  (no changes)

#=== ERROR while compiling coq-tactician-stdlib.8.13.dev ====================================#
"/tactician-patch": command not found.

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
The following actions failed
  build coq-tactician-stdlib 8.13.dev

No changes have been performed
```

**Comment by LasseBlaauwbroek** [comment]
Thanks for the report @sgodwincs. This error happens because the development opam files in `opam-coq-archive` are out of date (unfortunately we don't have an automated test for this particular problem). I've opened a pull request to update them here: https://github.com/coq/opam-coq-archive/pull/1967.

I see that you are using the development version of Tactician (version `coq-tactician.8.13.dev`). This version is generally not optimized for use by end-users. So unless you are planning to hack on Tactician itself, I recommend that you stay with the latest beta release `coq-tactician.1.0~beta1+8.13`.

**Comment by sgodwincs** [comment]
Thanks! I'm new to Coq and opam, so I'm not sure how I ended up on the dev version. I believe I executed the commands verbatim, but I guess I deviated somewhere.

Anyways, thanks for the quick followup, I look forward to messing around with this!
